### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by scottgonzalez** [bramstein/node-browserstack#3]
Hey @bramstein. Would you be interested in collaborating on https://www.npmjs.com/package/browserstack rather than maintaining your own module? Having several browserstack modules on npm forces users to evaluate the available options, which can result in lots of cumulative wasted time for developers. Working together to build a best of breed module would improve the situation for the whole community.

**Comment by bramstein** [comment]
@scottgonzalez I'd be happy to shut this project down. I'm no longer using or maintaining it. Feel free to use any of the code if it is useful.

**Comment by scottgonzalez** [comment]
In that case, would you mind changing the README stating that this module is deprecated with a pointer to the `browserstack` module? I can send a PR if you're good with that. Once the README is updated, we should release v0.2.3 so npmjs.com gets updated.

**Comment by bramstein** [comment]
@scottgonzalez A PR would be great. I can push the update to npm. Thanks!

**Comment by scottgonzalez** [comment]
Done! #4

**Comment by scottgonzalez** [comment]
This was resolved a while ago.
